apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: infra-namespaces
    - name: infra-helmrepositories
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cert-manager/dev-align-arm64/
  prune: false
  wait: true
  timeout: 5m0s
