serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

prometheusRule:
  enabled: true
  labels:
    release: kube-prometheus-stack

ingester:
  persistence:
    enabled: true
    claims:
      - name: data
        size: 100Gi
        storageClass: openebs-zfspv-default

querier:
  persistence:
    enabled: true
    size: 100Gi
    storageClass: openebs-zfspv-default

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: nephtek-com-issuer
  hosts:
    - loki.nas.nephtek.com
  tls:
    - secretName: loki-tls
      hosts:
        - loki.nas.nephtek.com

gateway:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: nephtek-com-issuer
    hosts:
      - loki-gateway.nas.nephtek.com
    tls:
      - secretName: loki-gateway-tls
        hosts:
          - loki-gateway.nas.nephtek.com

basicAuth:
  enabled: true
  username: lokiusser
