apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: tempo-distributed-base-config
    files:
      - values.base.yaml
generatorOptions:
  disableNameSuffixHash: true
