apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - crd.yaml
configMapGenerator:
  - name: cert-manager-base-config
    files:
      - values.base.yaml
generatorOptions:
  disableNameSuffixHash: true
