apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 5m
  chart:
    spec:
      version: "1.x"
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 60m
  valuesFrom:
    - kind: ConfigMap
      name: tempo-base-config
      valuesKey: values.base.yaml
    - kind: ConfigMap
      name: tempo-config
      valuesKey: values.yaml
